version: '3.8'

services:
  db:
    image: postgres:latest
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      retries: 5

  app:
    build: .
    command: scripts/startup.sh
    environment: 
      - DATABASE_URL=postgresql+psycopg2://admin:1234@db:5432/test
    volumes:
      - "./:/app"
    depends_on:
      db: 
        condition: service_healthy

